std="lua53"
files["snmp.lua"]={
	allow_defined_top = true,
	module = true,
	ignore={"612","611","621","23/_.*_","21/_.*_"},	
	read_globals={
		-- nm_snmp.c
		"inittrap",
		"gettrapd",
		"init",
		"_open",
		"close",
		"get",
		"getnext",
		"getbulk",
		"asynch_get",
		"asynch_getnext",
		"asynch_getbulk",
		"set",
		"asynch_set",
		"inform",
		"asynch_inform",
		"wait",
		"event",
		"idle",
		"loop",
		"sprint_variable",
		"sprint_value",
		"getversion",
		"createkey",
		"createlocalkey",
		"keychange",
		"details",
		"removeuser",
		-- except.c
		"newtry",
		"protect",
		-- nm_c64.c
		"counter64",
	},
}
